[package]
name = "rodbus_ffi_java"
version = "1.0.0-alpha6"
authors = ["Step Function I/O LLC <info@stepfunc.io>"]
edition = "2021"
build = "build.rs"

[lib]
crate-type = ["cdylib"]

[dependencies]
jni = "0.19"
rodbus-ffi = { path = "../rodbus-ffi" }

[build-dependencies]
rodbus-schema = { path = "../rodbus-schema" }
java-oo-bindgen = { git = "https://github.com/stepfunc/oo_bindgen.git", tag = "0.2.1" }