[package]
name = "rodbus"
version = "1.0.0-alpha5"
authors = ["Adam Crain <adam@stepfunc.io>", "Émile Grégoire <emile@stepfunc.io>"]
edition = "2021"
description = "A high-performance async implementation of the Modbus protocol using tokio"
keywords = ["modbus", "ics", "industrial", "plc", "security"]
categories = ["network-programming"]
repository = "https://github.com/stepfunc/rodbus"
readme = "../README.md"

[dependencies]
crc = "2.0"
tokio-mock = { git = "https://github.com/stepfunc/tokio-mock.git", branch = "feature/simplify-io" }
tokio-serial = "5.4"
tracing = "0.1"

# TLS dependencies
pem = { version = "1.0", optional = true }
pkcs8 = { version = "0.7", features = ["encryption", "pem", "std"], optional = true }
rasn = { git = "https://github.com/stepfunc/rasn.git", tag = "0.1.2", optional = true }
tokio-rustls = { version = "0.23", features = ["dangerous_configuration", "tls12"], default-features = false, optional = true }

[dev-dependencies]
tokio = { version = "1.5", features = ["rt-multi-thread", "macros"] }
tokio-stream = "0.1"
tokio-util = { version = "0.6", features = ["codec"] }
tracing-subscriber = "0.2"

[features]
default = ["tls"]
tls = ["pem", "pkcs8", "rasn", "tokio-rustls"]
