[package]
name = "rodbus"
version = "0.9.1"
authors = ["Adam Crain <adam@stepfunc.io>", "Émile Grégoire <emile@stepfunc.io>"]
edition = "2018"
description = "A high-performance async implementation of the Modbus protocol using tokio"
keywords = ["modbus", "ics", "industrial", "plc", "security"]
categories = ["network-programming"]
repository = "https://github.com/stepfunc/rodbus"
readme = "../README.md"

[dependencies]
pem = "1.0"
pkcs8 = { version = "0.7", features = ["encryption", "pem", "std"] }
rasn = { git = "https://github.com/stepfunc/rasn.git", tag = "0.1.2" }
tokio-mock = { git = "https://github.com/stepfunc/tokio-mock.git", tag = "0.1.0" }
tokio-rustls = { version = "0.23", features = ["dangerous_configuration", "tls12"], default-features = false }
tracing = "0.1"

[dev-dependencies]
tokio = { version = "1.5", features = ["rt-multi-thread", "macros"] }
tokio-stream = "0.1"
tokio-util = { version = "0.6", features = ["codec"] }
tracing-subscriber = "0.2"
