[workspace]

members = [
  "rodbus",
  "rodbus-client",
  "ffi/rodbus-bindings",
  "ffi/rodbus-ffi",
  "ffi/rodbus-ffi-java",
  "ffi/rodbus-schema",
]

[profile.release]
lto=true

[patch.crates-io]
oo-bindgen = { git = "https://github.com/stepfunc/oo_bindgen.git", branch = "feature/more-generic-promise" }