[package]
name = "rodbus-schema"
# this is the version that all the FFI libraries get, since it's in their schema
version = "1.1.0-rc1"
authors = ["Step Function I/O LLC <info@stepfunc.io>"]
edition = "2021"
license = "GPL-3.0-only"
description = "oobindgen schema for Rodbus"
keywords = ["ffi", "c", "modbus", "ics", "industrial", "plc", "security"]
categories = ["network-programming"]
repository = "https://github.com/stepfunc/rodbus"
readme = "../README.md"

[dependencies]
oo-bindgen = { git = "https://github.com/stepfunc/oo_bindgen.git", tag = "0.5.0" }
tracing-ffi-schema = { git = "https://github.com/stepfunc/tracing-ffi.git", tag = "0.3.0" }
tokio-ffi-schema = { git = "https://github.com/stepfunc/tokio-ffi.git", tag = "0.3.0" }
