[package]
name = "rodbus-client"
version = "0.9.0"
authors = ["Adam Crain <adam@stepfunc.io>", "Émile Grégoire <emile@stepfunc.io>"]
edition = "2018"
description = "A command line program for making Modbus client requests using the Rodbus crate"
keywords = ["modbus", "ics", "industrial", "plc", "security"]
categories = ["network-programming"]
repository = "https://github.com/stepfunc/rodbus"
readme = "README.md"

[[bin]]
name = "rodbus-client"
path = "src/main.rs"

[dependencies]
rodbus = { path = "../rodbus", version = "0.9.0" }
clap = "2.33"
tokio = { version = "1.5", features = ["macros", "time"] }
tracing = "0.1"
tracing-subscriber = "0.2"
