[package]
name = "rodbus-ffi"
version = "0.9.1"
authors = ["Adam Crain <adam@stepfunc.io>", "Émile Grégoire <emile@stepfunc.io>"]
edition = "2018"
description = "FFI for Rodbus"
keywords = ["ffi", "c", "modbus", "ics", "industrial", "plc", "security"]
categories = ["network-programming"]
repository = "https://github.com/stepfunc/rodbus"
readme = "../README.md"

[lib]
crate-type = ["rlib", "staticlib", "cdylib"]

[dependencies]
lazy_static = "1.0"
tracing = "0.1"
tracing-core = "0.1"
tracing-subscriber = "0.2"
rodbus = { path = "../../rodbus" }
tokio = { version = "1.5", features = ["rt-multi-thread"]}
num_cpus = "1"

[build-dependencies]
rodbus-schema = { path = "../rodbus-schema" }
rust-oo-bindgen = { git = "https://github.com/stepfunc/oo_bindgen.git", tag = "0.1.5" }
