[package]
name = "rodbus-bindings"
version = "1.1.0-rc1"
authors = ["Step Function I/O LLC <info@stepfunc.io>"]
edition = "2021"
description = "oobindgen schema for Rodbus"
keywords = ["ffi", "c", "modbus", "ics", "industrial", "plc", "security"]
categories = ["network-programming"]
repository = "https://github.com/stepfunc/rodbus"
readme = "../README.md"

[dependencies]
oo-bindgen = "0.6"
rodbus-schema = { path = "../rodbus-schema" }
tracing = "^0.1"
tracing-subscriber = "^0.3"

