[package]
name = "rodbus-bindings"
version = "1.0.0"
authors = ["Step Function I/O LLC <info@stepfunc.io>"]
edition = "2021"
license = "GPL-3.0-only"
description = "oobindgen schema for Rodbus"
keywords = ["ffi", "c", "modbus", "ics", "industrial", "plc", "security"]
categories = ["network-programming"]
repository = "https://github.com/stepfunc/rodbus"
readme = "../README.md"

[dependencies]
ci-script = { git = "https://github.com/stepfunc/oo_bindgen.git", tag = "0.5.0" }
rodbus-schema = { path = "../rodbus-schema" }
tracing = "^0.1"
tracing-subscriber = "^0.3"

